package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;

public final class XiaoNeiSai_005fbm_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final JspFactory _jspxFactory = JspFactory.getDefaultFactory();

  private static java.util.List _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.AnnotationProcessor _jsp_annotationprocessor;

  public Object getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_annotationprocessor = (org.apache.AnnotationProcessor) getServletConfig().getServletContext().getAttribute(org.apache.AnnotationProcessor.class.getName());
  }

  public void _jspDestroy() {
  }

  public void _jspService(HttpServletRequest request, HttpServletResponse response)
        throws java.io.IOException, ServletException {

    PageContext pageContext = null;
    HttpSession session = null;
    ServletContext application = null;
    ServletConfig config = null;
    JspWriter out = null;
    Object page = this;
    JspWriter _jspx_out = null;
    PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=gb2312");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Transitional//EN\" \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd\">\r\n");
      out.write("\r\n");
      out.write("<html xmlns=\"http://www.w3.org/1999/xhtml\">\r\n");
      out.write("\t<head>\r\n");
      out.write("\t\t<meta http-equiv=\"Content-Type\" content=\"text/html; charset=gb2312\" />\r\n");
      out.write("\t\t<title>数学建模协会新会员注册</title>\r\n");
      out.write("\r\n");
      out.write("\t\t<link REL=stylesheet href=\"1.css\" type=\"text/css\">\r\n");
      out.write("\t\t<script language=\"JavaScript\">\r\n");
      out.write("\t\t\r\n");
      out.write("\r\n");
      out.write("\t\tvar flag_name_1 = 0;\r\n");
      out.write("\t\tvar flag_txm_1 = 0;\r\n");
      out.write("\t\tvar flag_number_1 = 0;\r\n");
      out.write("\t\tvar flag_pwd_1 = 0;\r\n");
      out.write("\t\tvar flag_repwd_1 = 0;\r\n");
      out.write("\t\tvar flag_major_1 = 0;\r\n");
      out.write("\t\tvar flag_qq_1 = 0;\r\n");
      out.write("\t\tvar flag_tel_1 = 0;\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tvar flag_name_2 = 0;\r\n");
      out.write("\t\tvar flag_txm_2 = 0;\r\n");
      out.write("\t\tvar flag_number_2 = 0;\r\n");
      out.write("\t\tvar flag_pwd_2 = 0;\r\n");
      out.write("\t\tvar flag_repwd_2 = 0;\r\n");
      out.write("\t\tvar flag_major_2 = 0;\r\n");
      out.write("\t\tvar flag_qq_2 = 0;\r\n");
      out.write("\t\tvar flag_tel_2 = 0;\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tvar flag_name_3 = 0;\r\n");
      out.write("\t\tvar flag_txm_3 = 0;\r\n");
      out.write("\t\tvar flag_number_3 = 0;\r\n");
      out.write("\t\tvar flag_pwd_3 = 0;\r\n");
      out.write("\t\tvar flag_repwd_3 = 0;\r\n");
      out.write("\t\tvar flag_major_3 = 0;\r\n");
      out.write("\t\tvar flag_qq_3 = 0;\r\n");
      out.write("\t\tvar flag_tel_3 = 0;\r\n");
      out.write("\t\t\r\n");
      out.write("\tfunction isWhiteWpace(s) {\r\n");
      out.write("\tvar whitespace = \"\\t\\n\\r\";\r\n");
      out.write("\tvar i;\r\n");
      out.write("\tfor (i = 0; i < s.length; i++) {\r\n");
      out.write("\t\tvar c = s.charAt(i);\r\n");
      out.write("\t\tif (whitespace.indexOf(c) >= 0) {\r\n");
      out.write("\t\t\treturn true;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("\treturn false;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function check_name_1() {\r\n");
      out.write("\tif (isWhiteWpace(form1.name_1.value)) {\r\n");
      out.write("\t\tdocument.getElementById(\"nameErr_1\").innerHTML = \"<font color='red'>请输入正确的姓名，姓名里不能含有空格</font>\";\r\n");
      out.write("\t\treturn false;\r\n");
      out.write("\t}\r\n");
      out.write("\tif (form1.name_1.value == \"\") {\r\n");
      out.write("\t\tdocument.getElementById(\"nameErr_1\").innerHTML = \"<font color='red'>请输入姓名，姓名不能为空！</font>\";\r\n");
      out.write("\t\treturn false;\r\n");
      out.write("\t}\r\n");
      out.write("\tdocument.getElementById(\"nameErr_1\").innerHTML = \"\";\r\n");
      out.write("\tflag_name_1 = 1;\r\n");
      out.write("\treturn true;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("function check_name_2() {\r\n");
      out.write("\tif (isWhiteWpace(form1.name_2.value)) {\r\n");
      out.write("\t\tdocument.getElementById(\"nameErr_2\").innerHTML = \"<font color='red'>请输入正确的姓名，姓名里不能含有空格</font>\";\r\n");
      out.write("\t\treturn false;\r\n");
      out.write("\t}\r\n");
      out.write("\tif (form1.name_2.value == \"\") {\r\n");
      out.write("\t\tdocument.getElementById(\"nameErr_2\").innerHTML = \"<font color='red'>请输入姓名，姓名不能为空！</font>\";\r\n");
      out.write("\t\treturn false;\r\n");
      out.write("\t}\r\n");
      out.write("\tdocument.getElementById(\"nameErr_2\").innerHTML = \"\";\r\n");
      out.write("\tflag_name_2 = 1;\r\n");
      out.write("\treturn true;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("function check_name_3() {\r\n");
      out.write("\tif (isWhiteWpace(form1.name_3.value)) {\r\n");
      out.write("\t\tdocument.getElementById(\"nameErr_3\").innerHTML = \"<font color='red'>请输入正确的姓名，姓名里不能含有空格</font>\";\r\n");
      out.write("\t\treturn false;\r\n");
      out.write("\t}\r\n");
      out.write("\tif (form1.name_3.value == \"\") {\r\n");
      out.write("\t\tdocument.getElementById(\"nameErr_3\").innerHTML = \"<font color='red'>请输入姓名，姓名不能为空！</font>\";\r\n");
      out.write("\t\treturn false;\r\n");
      out.write("\t}\r\n");
      out.write("\tdocument.getElementById(\"nameErr_3\").innerHTML = \"\";\r\n");
      out.write("\tflag_name_3 = 1;\r\n");
      out.write("\treturn true;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("function check_txm_1() {\r\n");
      out.write("\tif (form1.txm_1.value == \"\") {\r\n");
      out.write("\t\tdocument.getElementById(\"txmErr_1\").innerHTML = \"<font color='red'>请输入条形码</font>\";\r\n");
      out.write("\t\treturn false;\r\n");
      out.write("\t}\r\n");
      out.write("\tdocument.getElementById(\"txmErr_1\").innerHTML = \"\";\r\n");
      out.write("\tflag_txm_1 = 1;\r\n");
      out.write("\treturn true;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("function check_txm_2() {\r\n");
      out.write("\tif (form1.txm_2.value == \"\") {\r\n");
      out.write("\t\tdocument.getElementById(\"txmErr_2\").innerHTML = \"<font color='red'>请输入条形码</font>\";\r\n");
      out.write("\t\treturn false;\r\n");
      out.write("\t}\r\n");
      out.write("\tdocument.getElementById(\"txmErr_2\").innerHTML = \"\";\r\n");
      out.write("\tflag_txm_2 = 1;\r\n");
      out.write("\treturn true;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function check_txm_3() {\r\n");
      out.write("\tif (form1.txm_3.value == \"\") {\r\n");
      out.write("\t\tdocument.getElementById(\"txmErr_3\").innerHTML = \"<font color='red'>请输入条形码</font>\";\r\n");
      out.write("\t\treturn false;\r\n");
      out.write("\t}\r\n");
      out.write("\tdocument.getElementById(\"txmErr_3\").innerHTML = \"\";\r\n");
      out.write("\tflag_txm_3 = 1;\r\n");
      out.write("\treturn true;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("function check_number_1() {\r\n");
      out.write("\tif (form1.number_1.value.length != 9) {\r\n");
      out.write("\t\tdocument.getElementById(\"numberErr_1\").innerHTML = \"<font color='red'>请输入正确学号</font>\";\r\n");
      out.write("\t\treturn false;\r\n");
      out.write("\t}\r\n");
      out.write("\tdocument.getElementById(\"numberErr_1\").innerHTML = \"\";\r\n");
      out.write("\tflag_number_1 = 1;\r\n");
      out.write("\treturn true;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function check_number_2() {\r\n");
      out.write("\tif (form1.number_2.value.length != 9) {\r\n");
      out.write("\t\tdocument.getElementById(\"numberErr_2\").innerHTML = \"<font color='red'>请输入正确学号</font>\";\r\n");
      out.write("\t\treturn false;\r\n");
      out.write("\t}\r\n");
      out.write("\tdocument.getElementById(\"numberErr_2\").innerHTML = \"\";\r\n");
      out.write("\tflag_number_2 = 1;\r\n");
      out.write("\treturn true;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function check_number_3() {\r\n");
      out.write("\tif (form1.number_3.value.length != 9) {\r\n");
      out.write("\t\tdocument.getElementById(\"numberErr_3\").innerHTML = \"<font color='red'>请输入正确学号</font>\";\r\n");
      out.write("\t\treturn false;\r\n");
      out.write("\t}\r\n");
      out.write("\tdocument.getElementById(\"numberErr_3\").innerHTML = \"\";\r\n");
      out.write("\tflag_number_3 = 1;\r\n");
      out.write("\treturn true;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("function check_major_1() {\r\n");
      out.write("\tif (form1.major_1.value == \"\") {\r\n");
      out.write("\t\tdocument.getElementById(\"majorErr_1\").innerHTML = \"<font color='red'>请输入专业</font>\";\r\n");
      out.write("\t\treturn false;\r\n");
      out.write("\t}\r\n");
      out.write("\tdocument.getElementById(\"majorErr_1\").innerHTML = \"\";\r\n");
      out.write("\tflag_major_1 = 1;\r\n");
      out.write("\treturn true;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function check_major_2() {\r\n");
      out.write("\tif (form1.major_2.value == \"\") {\r\n");
      out.write("\t\tdocument.getElementById(\"majorErr_2\").innerHTML = \"<font color='red'>请输入专业</font>\";\r\n");
      out.write("\t\treturn false;\r\n");
      out.write("\t}\r\n");
      out.write("\tdocument.getElementById(\"majorErr_2\").innerHTML = \"\";\r\n");
      out.write("\tflag_major_2 = 1;\r\n");
      out.write("\treturn true;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function check_major_3() {\r\n");
      out.write("\tif (form1.major_3.value == \"\") {\r\n");
      out.write("\t\tdocument.getElementById(\"majorErr_3\").innerHTML = \"<font color='red'>请输入专业</font>\";\r\n");
      out.write("\t\treturn false;\r\n");
      out.write("\t}\r\n");
      out.write("\tdocument.getElementById(\"majorErr_3\").innerHTML = \"\";\r\n");
      out.write("\tflag_major_3 = 1;\r\n");
      out.write("\treturn true;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("function check_tel_1() {\r\n");
      out.write("\tif (form1.tel_1.value == \"\") {\r\n");
      out.write("\t\tdocument.getElementById(\"telErr_1\").innerHTML = \"<font color='red'>请输入联系电话！</font>\";\r\n");
      out.write("\t\treturn false;\r\n");
      out.write("\t}\r\n");
      out.write("\tif (form1.tel_1.value.length != 11) {\r\n");
      out.write("\t\tdocument.getElementById(\"telErr_1\").innerHTML = \"<font color='red'>电话号码位数没有11位</font>\";\r\n");
      out.write("\t\treturn false;\r\n");
      out.write("\t}\r\n");
      out.write("\tdocument.getElementById(\"telErr_1\").innerHTML = \"\";\r\n");
      out.write("\tflag_tel_1 = 1;\r\n");
      out.write("\treturn true;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("function check_tel_2() {\r\n");
      out.write("\tif (form1.tel_2.value == \"\") {\r\n");
      out.write("\t\tdocument.getElementById(\"telErr_2\").innerHTML = \"<font color='red'>请输入联系电话！</font>\";\r\n");
      out.write("\t\treturn false;\r\n");
      out.write("\t}\r\n");
      out.write("\tif (form1.tel_2.value.length != 11) {\r\n");
      out.write("\t\tdocument.getElementById(\"telErr_2\").innerHTML = \"<font color='red'>电话号码位数没有11位</font>\";\r\n");
      out.write("\t\treturn false;\r\n");
      out.write("\t}\r\n");
      out.write("\tdocument.getElementById(\"telErr_2\").innerHTML = \"\";\r\n");
      out.write("\tflag_tel_2 = 1;\r\n");
      out.write("\treturn true;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function check_tel_3() {\r\n");
      out.write("\tif (form1.tel_3.value == \"\") {\r\n");
      out.write("\t\tdocument.getElementById(\"telErr_3\").innerHTML = \"<font color='red'>请输入联系电话！</font>\";\r\n");
      out.write("\t\treturn false;\r\n");
      out.write("\t}\r\n");
      out.write("\tif (form1.tel_3.value.length != 11) {\r\n");
      out.write("\t\tdocument.getElementById(\"telErr_3\").innerHTML = \"<font color='red'>电话号码位数没有11位</font>\";\r\n");
      out.write("\t\treturn false;\r\n");
      out.write("\t}\r\n");
      out.write("\tdocument.getElementById(\"telErr_3\").innerHTML = \"\";\r\n");
      out.write("\tflag_tel_3 = 1;\r\n");
      out.write("\treturn true;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function check()\r\n");
      out.write(" {\r\n");
      out.write("\t\r\n");
      out.write("\tif (flag_name_1 == 0)  {alert(\"组长姓名填写有误，请重新填写！\"); } \r\n");
      out.write("\t   else  if (flag_txm_1 == 0) {alert(\"组长条形码填写有误，请重新填写！\");}\t\r\n");
      out.write("\t        else if (flag_number_1 == 0) {alert(\"组长学号填写有误，请重新填写！\");} \r\n");
      out.write("\t           else if (flag_major_1 == 0) {alert(\"组长专业填写有误，请重新填写！\");} \r\n");
      out.write("\t              else if (flag_tel_1 == 0) {alert(\"组长联系电话填写有误，请重新填写！\");}\r\n");
      out.write("\t\t\t\t\telse if (flag_name_2 == 0) {alert(\"组员1姓名填写有误，请重新填写！\");} \r\n");
      out.write("\t\t\t\t\t  else if (flag_txm_2 == 0) {alert(\"组员1条形码填写有误，请重新填写！\");}\t\r\n");
      out.write("\t\t\t\t\t    else if (flag_number_2 == 0) {alert(\"组员1学号填写有误，请重新填写！\");} \r\n");
      out.write("\t\t\t\t\t      else if (flag_major_2 == 0) {alert(\"组员1专业填写有误，请重新填写！\");} \r\n");
      out.write("\t\t\t\t\t         else if (flag_tel_2 == 0) {alert(\"组员1联系电话填写有误，请重新填写！\");}\r\n");
      out.write("                                else if (flag_name_3 == 0) {alert(\"组员2姓名填写有误，请重新填写！\");} \r\n");
      out.write("                                   else if (flag_txm_3 == 0) {alert(\"组员2条形码填写有误，请重新填写！\");}\r\n");
      out.write("                                     else if (flag_number_3 == 0) {alert(\"组员2学号填写有误，请重新填写！\");}\r\n");
      out.write("                                       else if (flag_major_3 == 0) {alert(\"组员2专业填写有误，请重新填写！\");} \r\n");
      out.write("                                         else  if (flag_tel_3 == 0) {alert(\"组员2联系电话填写有误，请重新填写！\");}\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t</script>\r\n");
      out.write("\t</head>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<body>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t<form name=\"form1\" action=\"XiaoNeiSai_bm_deal.jsp\" method=\"post\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t<table width=\"800\" height=\"683\" border=\"1\" align=\"center\"\r\n");
      out.write("\t\t\t\tbackground=\"images/1.png\" bordercolor=\"#9966FF\">\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td colspan=\"3\" height=\"30\" id=\"x1\">\r\n");
      out.write("\t\t\t\t\t\t<center>\r\n");
      out.write("\t\t\t\t\t\t\t数学建模校内选拔赛报名\r\n");
      out.write("\t\t\t\t\t\t</center>\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td rowspan=\"8\" width=\"100\" align=\"center\" id=\"x2\">\r\n");
      out.write("\t\t\t\t\t\t组长\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<td width=\"\" height=\"30\" align=\"center\" id=\"x2\">\r\n");
      out.write("\t\t\t\t\t\t姓名\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t<td width=\"\">\r\n");
      out.write("\t\t\t\t\t\t<input id=\"x3\" type=\"text\" name=\"name_1\" onblur=\"check_name_1()\">\r\n");
      out.write("\t\t\t\t\t\t<span id=\"nameErr_1\"></span>\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<td width=\"210\" height=\"30\" align=\"center\" id=\"x2\">\r\n");
      out.write("\t\t\t\t\t\t学号\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t<td width=\"463\">\r\n");
      out.write("\t\t\t\t\t\t<input id=\"x3\" type=\"text\" name=\"number_1\"\r\n");
      out.write("\t\t\t\t\t\t\tonblur=\"check_number_1()\">\r\n");
      out.write("\t\t\t\t\t\t<span id=\"numberErr_1\"></span>\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td width=\"210\" height=\"30\" align=\"center\" id=\"x2\">\r\n");
      out.write("\t\t\t\t\t\t条形码\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t<td width=\"463\">\r\n");
      out.write("\t\t\t\t\t\t<input id=\"x3\" type=\"text\" name=\"txm_1\" onblur=\"check_txm_1()\">\r\n");
      out.write("\t\t\t\t\t\t<span id=\"txmErr_1\"></span>\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td width=\"210\" height=\"30\" align=\"center\" id=\"x2\">\r\n");
      out.write("\t\t\t\t\t\t性别\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t<td width=\"463\" id=\"x2\">\r\n");
      out.write("\t\t\t\t\t\t<input type=\"radio\" value=\"男\" checked name=\"sex_1\">\r\n");
      out.write("\t\t\t\t\t\t\t男 &nbsp;&nbsp; \r\n");
      out.write("\t\t\t\t\t\t<input type=\"radio\" value=\"女\" name=\"sex_1\">\r\n");
      out.write("\t\t\t\t\t\t\t女 \r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td width=\"210\" height=\"30\" align=\"center\" id=\"x2\">\r\n");
      out.write("\t\t\t\t\t\t年级\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t<select name=\"class_1\" id=\"x3\">\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"2010\" selected>\r\n");
      out.write("\t\t\t\t\t\t\t\t2010\r\n");
      out.write("\t\t\t\t\t\t\t</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"2011\">\r\n");
      out.write("\t\t\t\t\t\t\t\t2011\r\n");
      out.write("\t\t\t\t\t\t\t</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"2012\">\r\n");
      out.write("\t\t\t\t\t\t\t\t2012\r\n");
      out.write("\t\t\t\t\t\t\t</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"2013\">\r\n");
      out.write("\t\t\t\t\t\t\t\t2013\r\n");
      out.write("\t\t\t\t\t\t\t</option>\r\n");
      out.write("\t\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td width=\"210\" height=\"30\" align=\"center\" id=\"x2\">\r\n");
      out.write("\t\t\t\t\t\t专业\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t<td width=\"463\">\r\n");
      out.write("\t\t\t\t\t\t<input id=\"x3\" type=\"text\" name=\"major_1\" onblur=\"check_major_1()\">\r\n");
      out.write("\t\t\t\t\t\t<span id=\"majorErr_1\"></span>\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td width=\"210\" height=\"30\" align=\"center\" id=\"x2\">\r\n");
      out.write("\t\t\t\t\t\t学院\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t<select name=\"xueyuan_1\" id=\"x3\">\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"数学计算机科学学院\" SELECTED>\r\n");
      out.write("\t\t\t\t\t\t\t\t数学计算机科学学院\r\n");
      out.write("\t\t\t\t\t\t\t</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"文学院\">\r\n");
      out.write("\t\t\t\t\t\t\t\t文学院\r\n");
      out.write("\t\t\t\t\t\t\t</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"教育科学学院\">\r\n");
      out.write("\t\t\t\t\t\t\t\t教育科学学院\r\n");
      out.write("\t\t\t\t\t\t\t</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"经济管理学院\">\r\n");
      out.write("\t\t\t\t\t\t\t\t经济管理学院\r\n");
      out.write("\t\t\t\t\t\t\t</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"政法学院\">\r\n");
      out.write("\t\t\t\t\t\t\t\t政法学院\r\n");
      out.write("\t\t\t\t\t\t\t</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"社会学院\">\r\n");
      out.write("\t\t\t\t\t\t\t\t社会学院\r\n");
      out.write("\t\t\t\t\t\t\t</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"外国语学院\">\r\n");
      out.write("\t\t\t\t\t\t\t\t外国语学院\r\n");
      out.write("\t\t\t\t\t\t\t</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"音乐学院\">\r\n");
      out.write("\t\t\t\t\t\t\t\t音乐学院\r\n");
      out.write("\t\t\t\t\t\t\t</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"美术学院\">\r\n");
      out.write("\t\t\t\t\t\t\t\t美术学院\r\n");
      out.write("\t\t\t\t\t\t\t</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"传媒学院\">\r\n");
      out.write("\t\t\t\t\t\t\t\t传媒学院\r\n");
      out.write("\t\t\t\t\t\t\t</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"物理与电子信息学院\">\r\n");
      out.write("\t\t\t\t\t\t\t\t物理与电子信息学院\r\n");
      out.write("\t\t\t\t\t\t\t</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"化学与材料科学学院\">\r\n");
      out.write("\t\t\t\t\t\t\t\t化学与材料科学学院\r\n");
      out.write("\t\t\t\t\t\t\t</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"国土资源与旅游学院\">\r\n");
      out.write("\t\t\t\t\t\t\t\t国土资源与旅游学院\r\n");
      out.write("\t\t\t\t\t\t\t</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"体育学院\">\r\n");
      out.write("\t\t\t\t\t\t\t\t体育学院\r\n");
      out.write("\t\t\t\t\t\t\t</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"生命科学学院\">\r\n");
      out.write("\t\t\t\t\t\t\t\t生命科学学院\r\n");
      out.write("\t\t\t\t\t\t\t</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"环境科学学院\">\r\n");
      out.write("\t\t\t\t\t\t\t\t环境科学学院\r\n");
      out.write("\t\t\t\t\t\t\t</option>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t</script>\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td width=\"210\" height=\"30\" align=\"center\" id=\"x2\">\r\n");
      out.write("\t\t\t\t\t\t联系电话\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t<td width=\"463\">\r\n");
      out.write("\t\t\t\t\t\t<input id=\"x3\" type=\"text\" name=\"tel_1\" onblur=\"check_tel_1()\">\r\n");
      out.write("\t\t\t\t\t\t<span id=\"telErr_1\"></span>\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td rowspan=\"8\" width=\"100\" align=\"center\" id=\"x2\">\r\n");
      out.write("\t\t\t\t\t\t组员\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<td width=\"\" height=\"30\" align=\"center\" id=\"x2\">\r\n");
      out.write("\t\t\t\t\t\t姓名\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t<td width=\"\">\r\n");
      out.write("\t\t\t\t\t\t<input id=\"x3\" type=\"text\" name=\"name_2\" onblur=\"check_name_2()\">\r\n");
      out.write("\t\t\t\t\t\t<span id=\"nameErr_2\"></span>\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<td width=\"210\" height=\"30\" align=\"center\" id=\"x2\">\r\n");
      out.write("\t\t\t\t\t\t学号\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t<td width=\"463\">\r\n");
      out.write("\t\t\t\t\t\t<input id=\"x3\" type=\"text\" name=\"number_2\"\r\n");
      out.write("\t\t\t\t\t\t\tonblur=\"check_number_2()\">\r\n");
      out.write("\t\t\t\t\t\t<span id=\"numberErr_2\"></span>\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td width=\"210\" height=\"30\" align=\"center\" id=\"x2\">\r\n");
      out.write("\t\t\t\t\t\t条形码\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t<td width=\"463\">\r\n");
      out.write("\t\t\t\t\t\t<input id=\"x3\" type=\"text\" name=\"txm_2\" onblur=\"check_txm_2()\">\r\n");
      out.write("\t\t\t\t\t\t<span id=\"txmErr_2\"></span>\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td width=\"210\" height=\"30\" align=\"center\" id=\"x2\">\r\n");
      out.write("\t\t\t\t\t\t性别\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t<td width=\"463\" id=\"x2\">\r\n");
      out.write("\t\t\t\t\t\t<input type=\"radio\" value=\"男\" checked name=\"sex_2\">\r\n");
      out.write("\t\t\t\t\t\t\t男 &nbsp;&nbsp; \r\n");
      out.write("\t\t\t\t\t\t<input type=\"radio\" value=\"女\" name=\"sex_2\">\r\n");
      out.write("\t\t\t\t\t\t\t女 \r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td width=\"210\" height=\"30\" align=\"center\" id=\"x2\">\r\n");
      out.write("\t\t\t\t\t\t年级\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t<select name=\"class_2\" id=\"x3\">\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"2010\" selected>\r\n");
      out.write("\t\t\t\t\t\t\t\t2010\r\n");
      out.write("\t\t\t\t\t\t\t</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"2011\">\r\n");
      out.write("\t\t\t\t\t\t\t\t2011\r\n");
      out.write("\t\t\t\t\t\t\t</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"2012\">\r\n");
      out.write("\t\t\t\t\t\t\t\t2012\r\n");
      out.write("\t\t\t\t\t\t\t</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"2013\">\r\n");
      out.write("\t\t\t\t\t\t\t\t2013\r\n");
      out.write("\t\t\t\t\t\t\t</option>\r\n");
      out.write("\t\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td width=\"210\" height=\"30\" align=\"center\" id=\"x2\">\r\n");
      out.write("\t\t\t\t\t\t专业\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t<td width=\"463\">\r\n");
      out.write("\t\t\t\t\t\t<input id=\"x3\" type=\"text\" name=\"major_2\" onblur=\"check_major_2()\">\r\n");
      out.write("\t\t\t\t\t\t<span id=\"majorErr_2\"></span>\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td width=\"210\" height=\"30\" align=\"center\" id=\"x2\">\r\n");
      out.write("\t\t\t\t\t\t学院\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t<select name=\"xueyuan_2\" id=\"x3\">\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"数学计算机科学学院\" SELECTED>\r\n");
      out.write("\t\t\t\t\t\t\t\t数学计算机科学学院\r\n");
      out.write("\t\t\t\t\t\t\t</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"文学院\">\r\n");
      out.write("\t\t\t\t\t\t\t\t文学院\r\n");
      out.write("\t\t\t\t\t\t\t</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"教育科学学院\">\r\n");
      out.write("\t\t\t\t\t\t\t\t教育科学学院\r\n");
      out.write("\t\t\t\t\t\t\t</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"经济管理学院\">\r\n");
      out.write("\t\t\t\t\t\t\t\t经济管理学院\r\n");
      out.write("\t\t\t\t\t\t\t</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"政法学院\">\r\n");
      out.write("\t\t\t\t\t\t\t\t政法学院\r\n");
      out.write("\t\t\t\t\t\t\t</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"社会学院\">\r\n");
      out.write("\t\t\t\t\t\t\t\t社会学院\r\n");
      out.write("\t\t\t\t\t\t\t</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"外国语学院\">\r\n");
      out.write("\t\t\t\t\t\t\t\t外国语学院\r\n");
      out.write("\t\t\t\t\t\t\t</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"音乐学院\">\r\n");
      out.write("\t\t\t\t\t\t\t\t音乐学院\r\n");
      out.write("\t\t\t\t\t\t\t</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"美术学院\">\r\n");
      out.write("\t\t\t\t\t\t\t\t美术学院\r\n");
      out.write("\t\t\t\t\t\t\t</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"传媒学院\">\r\n");
      out.write("\t\t\t\t\t\t\t\t传媒学院\r\n");
      out.write("\t\t\t\t\t\t\t</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"物理与电子信息学院\">\r\n");
      out.write("\t\t\t\t\t\t\t\t物理与电子信息学院\r\n");
      out.write("\t\t\t\t\t\t\t</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"化学与材料科学学院\">\r\n");
      out.write("\t\t\t\t\t\t\t\t化学与材料科学学院\r\n");
      out.write("\t\t\t\t\t\t\t</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"国土资源与旅游学院\">\r\n");
      out.write("\t\t\t\t\t\t\t\t国土资源与旅游学院\r\n");
      out.write("\t\t\t\t\t\t\t</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"体育学院\">\r\n");
      out.write("\t\t\t\t\t\t\t\t体育学院\r\n");
      out.write("\t\t\t\t\t\t\t</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"生命科学学院\">\r\n");
      out.write("\t\t\t\t\t\t\t\t生命科学学院\r\n");
      out.write("\t\t\t\t\t\t\t</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"环境科学学院\">\r\n");
      out.write("\t\t\t\t\t\t\t\t环境科学学院\r\n");
      out.write("\t\t\t\t\t\t\t</option>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t</script>\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td width=\"210\" height=\"30\" align=\"center\" id=\"x2\">\r\n");
      out.write("\t\t\t\t\t\t联系电话\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t<td width=\"463\">\r\n");
      out.write("\t\t\t\t\t\t<input id=\"x3\" type=\"text\" name=\"tel_2\" onblur=\"check_tel_2()\">\r\n");
      out.write("\t\t\t\t\t\t<span id=\"telErr_2\"></span>\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td rowspan=\"8\" width=\"100\" align=\"center\" id=\"x2\">\r\n");
      out.write("\t\t\t\t\t\t组员\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<td width=\"\" height=\"30\" align=\"center\" id=\"x2\">\r\n");
      out.write("\t\t\t\t\t\t姓名\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t<td width=\"\">\r\n");
      out.write("\t\t\t\t\t\t<input id=\"x3\" type=\"text\" name=\"name_3\" onblur=\"check_name_3()\">\r\n");
      out.write("\t\t\t\t\t\t<span id=\"nameErr_3\"></span>\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<td width=\"210\" height=\"30\" align=\"center\" id=\"x2\">\r\n");
      out.write("\t\t\t\t\t\t学号\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t<td width=\"463\">\r\n");
      out.write("\t\t\t\t\t\t<input id=\"x3\" type=\"text\" name=\"number_3\"\r\n");
      out.write("\t\t\t\t\t\t\tonblur=\"check_number_3()\">\r\n");
      out.write("\t\t\t\t\t\t<span id=\"numberErr_3\"></span>\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td width=\"210\" height=\"30\" align=\"center\" id=\"x2\">\r\n");
      out.write("\t\t\t\t\t\t条形码\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t<td width=\"463\">\r\n");
      out.write("\t\t\t\t\t\t<input id=\"x3\" type=\"text\" name=\"txm_3\" onblur=\"check_txm_3()\">\r\n");
      out.write("\t\t\t\t\t\t<span id=\"txmErr_3\"></span>\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td width=\"210\" height=\"30\" align=\"center\" id=\"x2\">\r\n");
      out.write("\t\t\t\t\t\t性别\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t<td width=\"463\" id=\"x2\">\r\n");
      out.write("\t\t\t\t\t\t<input type=\"radio\" value=\"男\" checked name=\"sex_3\">\r\n");
      out.write("\t\t\t\t\t\t\t男 &nbsp;&nbsp; \r\n");
      out.write("\t\t\t\t\t\t<input type=\"radio\" value=\"女\" name=\"sex_3\">\r\n");
      out.write("\t\t\t\t\t\t\t女 \r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td width=\"210\" height=\"30\" align=\"center\" id=\"x2\">\r\n");
      out.write("\t\t\t\t\t\t年级\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t<select name=\"class_3\" id=\"x3\">\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"2010\" selected>\r\n");
      out.write("\t\t\t\t\t\t\t\t2010\r\n");
      out.write("\t\t\t\t\t\t\t</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"2011\">\r\n");
      out.write("\t\t\t\t\t\t\t\t2011\r\n");
      out.write("\t\t\t\t\t\t\t</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"2012\">\r\n");
      out.write("\t\t\t\t\t\t\t\t2012\r\n");
      out.write("\t\t\t\t\t\t\t</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"2013\">\r\n");
      out.write("\t\t\t\t\t\t\t\t2013\r\n");
      out.write("\t\t\t\t\t\t\t</option>\r\n");
      out.write("\t\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td width=\"210\" height=\"30\" align=\"center\" id=\"x2\">\r\n");
      out.write("\t\t\t\t\t\t专业\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t<td width=\"463\">\r\n");
      out.write("\t\t\t\t\t\t<input id=\"x3\" type=\"text\" name=\"major_3\" onblur=\"check_major_3()\">\r\n");
      out.write("\t\t\t\t\t\t<span id=\"majorErr_3\"></span>\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td width=\"210\" height=\"30\" align=\"center\" id=\"x2\">\r\n");
      out.write("\t\t\t\t\t\t学院\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t<select name=\"xueyuan_3\" id=\"x3\">\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"数学计算机科学学院\" SELECTED>\r\n");
      out.write("\t\t\t\t\t\t\t\t数学计算机科学学院\r\n");
      out.write("\t\t\t\t\t\t\t</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"文学院\">\r\n");
      out.write("\t\t\t\t\t\t\t\t文学院\r\n");
      out.write("\t\t\t\t\t\t\t</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"教育科学学院\">\r\n");
      out.write("\t\t\t\t\t\t\t\t教育科学学院\r\n");
      out.write("\t\t\t\t\t\t\t</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"经济管理学院\">\r\n");
      out.write("\t\t\t\t\t\t\t\t经济管理学院\r\n");
      out.write("\t\t\t\t\t\t\t</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"政法学院\">\r\n");
      out.write("\t\t\t\t\t\t\t\t政法学院\r\n");
      out.write("\t\t\t\t\t\t\t</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"社会学院\">\r\n");
      out.write("\t\t\t\t\t\t\t\t社会学院\r\n");
      out.write("\t\t\t\t\t\t\t</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"外国语学院\">\r\n");
      out.write("\t\t\t\t\t\t\t\t外国语学院\r\n");
      out.write("\t\t\t\t\t\t\t</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"音乐学院\">\r\n");
      out.write("\t\t\t\t\t\t\t\t音乐学院\r\n");
      out.write("\t\t\t\t\t\t\t</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"美术学院\">\r\n");
      out.write("\t\t\t\t\t\t\t\t美术学院\r\n");
      out.write("\t\t\t\t\t\t\t</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"传媒学院\">\r\n");
      out.write("\t\t\t\t\t\t\t\t传媒学院\r\n");
      out.write("\t\t\t\t\t\t\t</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"物理与电子信息学院\">\r\n");
      out.write("\t\t\t\t\t\t\t\t物理与电子信息学院\r\n");
      out.write("\t\t\t\t\t\t\t</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"化学与材料科学学院\">\r\n");
      out.write("\t\t\t\t\t\t\t\t化学与材料科学学院\r\n");
      out.write("\t\t\t\t\t\t\t</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"国土资源与旅游学院\">\r\n");
      out.write("\t\t\t\t\t\t\t\t国土资源与旅游学院\r\n");
      out.write("\t\t\t\t\t\t\t</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"体育学院\">\r\n");
      out.write("\t\t\t\t\t\t\t\t体育学院\r\n");
      out.write("\t\t\t\t\t\t\t</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"生命科学学院\">\r\n");
      out.write("\t\t\t\t\t\t\t\t生命科学学院\r\n");
      out.write("\t\t\t\t\t\t\t</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"环境科学学院\">\r\n");
      out.write("\t\t\t\t\t\t\t\t环境科学学院\r\n");
      out.write("\t\t\t\t\t\t\t</option>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t</script>\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td width=\"210\" height=\"30\" align=\"center\" id=\"x2\">\r\n");
      out.write("\t\t\t\t\t\t联系电话\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t<td width=\"463\">\r\n");
      out.write("\t\t\t\t\t\t<input id=\"x3\" type=\"text\" name=\"tel_3\" onblur=\"check_tel_3()\">\r\n");
      out.write("\t\t\t\t\t\t<span id=\"telErr_3\"></span>\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<td bordercolor=\"#FFFFFF\" colspan=\"3\" height=\"30\"  id=\"x3\">\r\n");
      out.write("\t\t\t\t<a href=\"Download.jsp\">比赛规则下载</a>\r\n");
      out.write("\t\t\t\t&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;\r\n");
      out.write("\t\t\t\t\t<input type=\"reset\" value=\"重置\" id=\"x4\">\r\n");
      out.write("\t\t\t\t\t\t&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<input type=\"submit\" value=\"提交\" id=\"x4\" onclick=\"check()\">\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td colspan=\"2\" height=\"170\" id=\"x3\"></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td colspan=\"3\" height=\"20\" id=\"x5\" align=\"center\">\r\n");
      out.write("\t\t\t\t\t\t安徽师范大学 数计学院 数学建模协会 \r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t<a href=\"administrator_yanzheng.jsp\">管理员登录</a>\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t</table>\r\n");
      out.write("\t\t</form>\r\n");
      out.write("\t</body>\r\n");
      out.write("</html>\r\n");
    } catch (Throwable t) {
      if (!(t instanceof SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
