package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;
import java.sql.*;

public final class HouTai_005fControl_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final JspFactory _jspxFactory = JspFactory.getDefaultFactory();

  private static java.util.List _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.AnnotationProcessor _jsp_annotationprocessor;

  public Object getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_annotationprocessor = (org.apache.AnnotationProcessor) getServletConfig().getServletContext().getAttribute(org.apache.AnnotationProcessor.class.getName());
  }

  public void _jspDestroy() {
  }

  public void _jspService(HttpServletRequest request, HttpServletResponse response)
        throws java.io.IOException, ServletException {

    PageContext pageContext = null;
    HttpSession session = null;
    ServletContext application = null;
    ServletConfig config = null;
    JspWriter out = null;
    Object page = this;
    JspWriter _jspx_out = null;
    PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=gb2312");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");

	String path = request.getContextPath();
	String basePath = request.getScheme() + "://"
			+ request.getServerName() + ":" + request.getServerPort()
			+ path + "/";

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<head>\r\n");
      out.write("\t\t<title>数学建模网站</title>\r\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"jquery-1.3.2.min.js\"></script>\r\n");
      out.write("\t\t<script type=text/javascript>\r\n");
      out.write("$(function(){\r\n");
      out.write("\t$('#mobanwang_com li').hover(function(){\r\n");
      out.write("\t\t$(this).children('ul').stop(true,true).show('slow');\r\n");
      out.write("\t},function(){\r\n");
      out.write("\t\t$(this).children('ul').stop(true,true).hide('slow');\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("\t$('#mobanwang_com li').hover(function(){\r\n");
      out.write("\t\t$(this).children('div').stop(true,true).show('slow');\r\n");
      out.write("\t},function(){\r\n");
      out.write("\t\t$(this).children('div').stop(true,true).hide('slow');\r\n");
      out.write("\t});\r\n");
      out.write("});\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t<style type=\"text/css\">\r\n");
      out.write("a:link {\r\n");
      out.write("\tcolor: #FFFFFF;\r\n");
      out.write("\ttext-decoration: none;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("a:visited {\r\n");
      out.write("\ttext-decoration: none;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("a:hover {\r\n");
      out.write("\ttext-decoration: underline;\r\n");
      out.write("\tcolor: #FF0000;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("a:active {\r\n");
      out.write("\ttext-decoration: none;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("* {\r\n");
      out.write("\tmargin: 0;\r\n");
      out.write("\tpadding: 0;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("body {\r\n");
      out.write("\tfont-family: Arial, Verdana, Helvetica, sans-serif;\r\n");
      out.write("\tfont-family: \"雅黑宋体\", \"微软雅黑\", \"新宋体\", \"宋体\";\r\n");
      out.write("\tfont-size: 1em;\r\n");
      out.write("\tfont-size: 17px;\r\n");
      out.write("\tcolor: #FFF;\r\n");
      out.write("\tbackground: #333333;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#time {\r\n");
      out.write("\tfont-family: \"宋体\";\r\n");
      out.write("\tfont-size: 1em;\r\n");
      out.write("\tfont-size: 17px;\r\n");
      out.write("\tcolor: #FFF;\r\n");
      out.write("\tbackground: #050505;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("a {\r\n");
      out.write("\tcolor: #FFF;\r\n");
      out.write("\ttext-decoration: none;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("ul {\r\n");
      out.write("\tlist-style: none;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#mobanwang_com {\r\n");
      out.write("\theight: 37px;\r\n");
      out.write("\tbackground: #333;\r\n");
      out.write("\tfont-size: 1.6em;\r\n");
      out.write("\ttext-align: center;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#mobanwang_com a {\r\n");
      out.write("\tfont-size: 0.65em;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#mobanwang_com li ul {\r\n");
      out.write("\tdisplay: none;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#mobanwang_com li ul li {\r\n");
      out.write("\tfloat: none;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("* html #mobanwang_com li ul li {\r\n");
      out.write("\tdisplay: inline;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#mobanwang_com li ul a {\r\n");
      out.write("\tfloat: none;\r\n");
      out.write("\theight: 32px;\r\n");
      out.write("\tline-height: 32px;\r\n");
      out.write("\tpadding: 0 10px;\r\n");
      out.write("\ttext-transform: capitalize;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#mobanwang_com .height-auto {\r\n");
      out.write("\tline-height: 15px;\r\n");
      out.write("\tpadding: 5px 10px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".second-menu,.third-menu,.fourth-menu {\r\n");
      out.write("\tposition: absolute;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".first-menu li {\r\n");
      out.write("\tfloat: left;\r\n");
      out.write("\tposition: relative;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".first-menu a {\r\n");
      out.write("\tfloat: left;\r\n");
      out.write("\tdisplay: block;\r\n");
      out.write("\tpadding: 0 15px;\r\n");
      out.write("\theight: 35px;\r\n");
      out.write("\tline-height: 35px;\r\n");
      out.write("\tbackground: #333;\r\n");
      out.write("\tborder-top: 1px solid #4a4a4a;\r\n");
      out.write("\tborder-left: 1px solid #4a4a4a;\r\n");
      out.write("\tborder-bottom: 1px solid #242424;\r\n");
      out.write("\tborder-right: 6px solid #242424;\r\n");
      out.write("\tfont-size: .7em;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".first-menu a:hover {\r\n");
      out.write("\tbackground: #4698ca;\r\n");
      out.write("\tborder-top: 1px solid #5db1e0;\r\n");
      out.write("\tborder-left: 1px solid #5db1e0;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".second-menu {\r\n");
      out.write("\ttop: 37px;\r\n");
      out.write("\tright: 0;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("* html .second-menu {\r\n");
      out.write("\tright: -1px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".second-menu a {\r\n");
      out.write("\tfont-size: 11px;\r\n");
      out.write("\t\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".second-menu a.mobanwang {\r\n");
      out.write("\tbackground: #3a3a3a url(image/mobanwang.gif) no-repeat right top;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".second-menu a.mobanwang:hover {\r\n");
      out.write("\tbackground: #4698ca url(image/mobanwang.gif) no-repeat right -32px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".second-menu a.mobanwang-02 {\r\n");
      out.write("\tbackground: #3a3a3a url(image/mobanwang.gif) no-repeat right -64px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".second-menu a.mobanwang-02:hover {\r\n");
      out.write("\tbackground: #4698ca url(image/mobanwang.gif) no-repeat right -110px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".third-menu,.fourth-menu {\r\n");
      out.write("\twidth: 177px;\r\n");
      out.write("\ttop: 0;\r\n");
      out.write("\tleft: 85px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".third-menu a {\r\n");
      out.write("\tfloat: left;\r\n");
      out.write("\tdisplay: block;\r\n");
      out.write("\tpadding: 0 15px;\r\n");
      out.write("\theight: 35px;\r\n");
      out.write("\tline-height: 35px;\r\n");
      out.write("\tbackground: #333;\r\n");
      out.write("\tborder-top: 1px solid #4a4a4a;\r\n");
      out.write("\tborder-left: 1px solid #4a4a4a;\r\n");
      out.write("\tborder-bottom: 1px solid #242424;\r\n");
      out.write("\tborder-right: 6px solid #242424;\r\n");
      out.write("\tfont-size: .7em;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#subMgm {\r\n");
      out.write("\twidth: 177px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#subMgm .third-menu {\r\n");
      out.write("\tleft: 177px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#subMgm .fourth-menu {\r\n");
      out.write("\tleft: 177px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#subMusic,#subNews {\r\n");
      out.write("\twidth: 177px;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("\t</head>\r\n");
      out.write("\t<body onload=\"clockon(bgclock)\" bgcolor=\"#FFFFFF\">\r\n");
      out.write("\t\t<table width=\"1047\" align=\"center\" border=\"1\">\r\n");
      out.write("\t\t\t<tr  style=\"background-image:url(photo/houtai.jpg)\" height=200\" width=\"930\">\r\n");
      out.write("\t\t\t\t<td colspan=\"3\" align=\"center\">\r\n");
      out.write("\t\t\t\t<font color=\"#FFFF00\" size=\"+6\" face=\"华文琥珀\">\t数学建模协会网站后台管理系统</font>\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td colspan=\"3\">\r\n");
      out.write("\t\t\t\t\t<ul id=\"mobanwang_com\" class=\"first-menu\">\r\n");
      out.write("\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"sxjm.jsp\" target=\"_self\">首 页</a>\r\n");
      out.write("\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t<li>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<a href=\"add_xiehuijianjie/add_xiehuijianjie.jsp\"target=\"_blank\"  >协会简介</a>\r\n");
      out.write("\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"#\" target=\"_self\">机构设置</a>\r\n");
      out.write("\t\t\t\t\t\t\t<ul id=\"subNews\" class=\"second-menu\">\r\n");
      out.write("\t\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t<a href=\"JiGouSheZhi/add_zhuxituan/add_zhuxituan.jsp\" target=\"_blank\">主席团</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t</li>\r\n");
      out.write("\r\n");
      out.write("<li>\r\n");
      out.write("<a href=\"JiGouSheZhi/add_bangongshi/add_bangongshi.jsp\" target=\"_blank\">办公室</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\r\n");
      out.write("<a href=\"JiGouSheZhi/add_xueyanbu/add_xueyanbu.jsp\" target=\"_blank\">学研部</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t<li>\t\t\t\t\t\t\t\t\r\n");
      out.write("<a href=\"JiGouSheZhi/add_cehuabu/add_cehuabu.jsp\" target=\"_blank\">策划部</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t</li>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<li>\r\n");
      out.write("<a href=\"JiGouSheZhi/add_xuanchuanbu/add_xuanchuanbu.jsp\" target=\"_blank\">宣传部</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t</li>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t<li>\r\n");
      out.write("<a  href=\"JiGouSheZhi/add_wailianbu/add_wailianbu.jsp\" target=\"_blank\">外联部</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li>\r\n");
      out.write("\r\n");
      out.write("<a href=\"JiGouSheZhi/add_renzhengbu/add_renzhengbu.jsp\" target=\"_blank\">认证部</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t</li>\r\n");
      out.write("<a href=\"JiGouSheZhi/add_wangluobu/add_wangluobu.jsp\" target=\"_blank\">网络部</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li>\r\n");
      out.write("<a href=\"JiGouSheZhi/add_caiwubu/add_caiwubu.jsp\" target=\"_blank\">财务部</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t</li>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"#\">新闻中心</a>\r\n");
      out.write("<ul id=\"subNews\" class=\"second-menu\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<a href=\"XinWenZhongXin/add_gonggao/add_gonggao.jsp\" class=\"mobanwang\" target=\"_blank\">通知公告</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<a href=\"XinWenZhongXin/add_xinwen/add_xinwen.jsp\" class=\"mobanwang\" target=\"_blank\">新闻动态</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<a href=\"XinWenZhongXin/add_jingcaituijian/add_jingcaituijian.jsp\" class=\"mobanwang\" target=\"_blank\">精彩推荐</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t</li>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"#\" class=\"mobanwang\">活动介绍</a>\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t<ul id=\"subNews\" class=\"second-menu\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<a href=\"HuoDongJieShao/add_quanguosai/add_quanguosai.jsp\" class=\"mobanwang\" target=\"_blank\">数学建模全国赛</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<a href=\"HuoDongJieShao/add_jianmojiangzuo/add_jianmojiangzuo.jsp\" class=\"mobanwang\" target=\"_blank\">数学建模知识讲座</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<a href=\"HuoDongJieShao/add_quweishuxue/add_quweishuxue.jsp\" class=\"mobanwang\" target=\"_blank\">趣味数学竞赛</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<a href=\"HuoDongJieShao/add_tiaozhansai/add_tiaozhansai.jsp\" class=\"mobanwang\" target=\"_blank\">网络挑战赛</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<a href=\"HuoDongJieShao/add_wuhusai/add_wuhusai.jsp\" class=\"mobanwang\" target=\"_blank\">芜湖高校联赛</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<a href=\"HuoDongJieShao/add_wocaiwoxuan/add_wocaiwoxuan.jsp\" class=\"mobanwang\" target=\"_blank\">我才我炫</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<a href=\"HuoDongJieShao/add_xiaoneixuanbasai/add_xiaoneixuanbasai.jsp\" class=\"mobanwang\" target=\"_blank\">校内选拔赛</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t</li>\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<a href=\"HuoDongJieShao/add_shuqipeixun/add_shuqipeixun.jsp\" class=\"mobanwang\" target=\"_blank\">数学建模暑期培训</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t</li>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"JianMoZhiShi/add_jianmozhishi/add_jianmozhishi.jsp\" class=\"mobanwang\" target=\"_blank\">建模知识</a>\r\n");
      out.write("\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"ChengJiZhanShi/quanguosai/add_quanguosai.jsp\" class=\"mobanwang\" target=\"_blank\">成绩展示</a>\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"LiuYanBan/liuyan_desc.jsp\" class=\"mobanwang\" target=\"_blank\">留言查看</a>\r\n");
      out.write("\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"#\" class=\"mobanwang\" >会员管理</a>\r\n");
      out.write("\t\t\t\t\t\t\t<ul id=\"subNews\" class=\"second-menu\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<a href=\"HY_info/HuiYuan_information.jsp\" class=\"mobanwang\" target=\"_blank\">会员注册查看</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<a href=\"HY_info/HuiYuan_delete.jsp\" class=\"mobanwang\" target=\"_blank\">删除会员</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<a href=\"HY_info/Suggestion_To_Us.jsp\" class=\"mobanwang\" target=\"_blank\">会员对我们的建议</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t</li>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"#\" class=\"mobanwang\" target=\"_blank\">条形码管理</a>\r\n");
      out.write("\t\t\t\t\t\t<ul id=\"subNews\" class=\"second-menu\">\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t<a href=\"TXM/HY_Regist/txm_info.jsp\" target=\"_blank\">条形码注册查看</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t</li>\r\n");
      out.write("<li>\r\n");
      out.write("\t\t\t\t\t\t<a href=\"TXM/HY_Regist/add_txm.jsp\"  target=\"_blank\">添加条形码</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t<a href=\"TXM/HY_Regist/txm_delete.jsp\"  target=\"_blank\">删除条形码</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("\t</body>\r\n");
      out.write("</html>\r\n");
    } catch (Throwable t) {
      if (!(t instanceof SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
